"""empty message

Revision ID: 45758f086da7
Revises: 7ed2d39a36d7
Create Date: 2020-03-13 11:52:32.419874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45758f086da7'
down_revision = '7ed2d39a36d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('modified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'modified_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
